name: Vedanova
pygments: true
excerpt_separator: "\n\n"
paginate: 5
paginate_files:
 - blog.html

#gems: [jekyll-pagination]

name: Vedanova
url: http://vedanova.com
author: Christoph Klocker
rss_post_limit: 15