name: Vedanova
pygments: true
excerpt_separator: "\n\n"
paginate: 5
paginate_path: blog/page:num
markdown: kramdown

#gems: [jekyll-pagination]

url: http://vedanova.com
author: Christoph Klocker
rss_post_limit: 15